plugins {
    id 'java'
}

group = 'project'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(path: ':services')
    implementation project(path: ':domain')
    implementation 'org.apache.activemq:activemq-all:5.17.6'
    implementation 'com.google.code.gson:gson:2.9.0'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}